### PR TITLE
JitPack support

### PR DESCRIPTION
**Pull request by GliczDev**

### CODE REVIEW

**Comment by ZockerAxel** [comment]
I'm not sure about this because of the legally questionable repo that hosts nms which is needed for jitpack to work. The owners of the repo are not affiliated with mojang and spigot only has the entire buildtools issue because of issues with Minecraft nms Code in the first place.

**Comment by GliczDev** [comment]
I can migrate this project to gradle and use [paperweight](https://github.com/PaperMC/paperweight) which resolves legality issues. The only issue is that I'd need to migrate spigot mappings to mojang mappings in the whole project. What do you think about it?

**Comment by ZockerAxel** [comment]
Could be an option but not something I want to decide right now.
I would also be fine with linking your repo for jitpack support if you are willing to maintain it.
As you don't seem to be bothered with the dependency being legally questionable that would be okay for me as I would not have to take care of it. What do you think?

**Comment by GliczDev** [comment]
For now, no problem!
However, I want to use mojang mappings on my server in the future, so I think I'll migrate it to paperweight for mojmap support sometime, then I'll maybe reopen my pr.

**Pull request closed without merging**
